{% set name = "tramway" %}
{% set version = "0.6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/TRamWAy/archive/v{{ version }}.tar.gz
  sha256: 420bacf86c55ad740e3d0348092e064c7797bbde749ac00ddc99a910131060a8

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - poetry
    - python
  run:
    - setuptools
    - hdf5
    - python
    - rwa-python =0.9.3
    - matplotlib-base
    - cvxopt
    - polytope
    - tqdm
    - scikit-image
    - stopit  # [not win]

test:
  imports:
    - tramway
  source_files:
    - tests/test_core.py
    - tests/test_analyzer.py
    - tests/test_analyzer_pipeline.py
  requires:
    - pytest
  commands:
    - pytest tests/test_core.py tests/test_analyzer.py::TestSptDataAccess tests/test_analyzer.py::TestTesseller tests/test_analyzer.py::TestIndexer tests/test_analyzer.py::TestAssignment tests/test_analyzer.py::TestSideEffects

about:
  home: https://github.com/DecBayComp/TRamWAy
  license: CECILL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'The RAndom Walk AnalYzer: analysis toolbox for localization microscopy data'
  doc_url: https://tramway.readthedocs.io/

extra:
  recipe-maintainers:
    - DecBayComp
